<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            [
                'name' => 'view_owner',
                'group_name' => 'Admin',
                'label' => 'View Owner',
                'description' => 'Can access the owner area.',
                'is_system' => true,
                'is_locked' => true,
            ],
            [
                'name' => 'view_admin',
                'group_name' => 'Admin',
                'label' => 'View Admin',
                'description' => 'Can access the admin area.',
                'is_system' => true,
                'is_locked' => true,
            ],
            [
                'name' => 'create_people',
                'group_name' => 'People',
                'label' => 'Create People',
                'description' => 'Can create people.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_people',
                'group_name' => 'People',
                'label' => 'Access People',
                'description' => 'Can access people information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_people',
                'group_name' => 'People',
                'label' => 'Read People',
                'description' => 'Can View peoples information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_people',
                'group_name' => 'People',
                'label' => 'Update People',
                'description' => 'Can update a persons information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_people',
                'group_name' => 'People',
                'label' => 'Delete People',
                'description' => 'Can delete a person.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_positions',
                'group_name' => 'Positions',
                'label' => 'Access Positions',
                'description' => 'Can access positions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_positions',
                'group_name' => 'Positions',
                'label' => 'Create Positions',
                'description' => 'Can create positions.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_positions',
                'group_name' => 'Positions',
                'label' => 'Read Positions',
                'description' => 'Can view positions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_positions',
                'group_name' => 'Positions',
                'label' => 'Update Positions',
                'description' => 'Can update positions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_positions',
                'group_name' => 'Positions',
                'label' => 'Delete a Position',
                'description' => 'Can delete positions.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_candidates',
                'group_name' => 'Candidates',
                'label' => 'Access Candidates',
                'description' => 'Can access candidates information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_candidates',
                'group_name' => 'Candidates',
                'label' => 'Create Candidates',
                'description' => 'Can create candidates.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_candidates',
                'group_name' => 'Candidates',
                'label' => 'Read Candidates',
                'description' => 'Can view a candidates information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_candidates',
                'group_name' => 'Candidates',
                'label' => 'Update Candidate',
                'description' => 'Can update candidates information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_candidates',
                'group_name' => 'Candidates',
                'label' => 'Delete Candidates',
                'description' => 'Can delete candidates.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_tickets',
                'group_name' => 'Tickets',
                'label' => 'Access Tickets',
                'description' => 'Can access tickets information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_tickets',
                'group_name' => 'Tickets',
                'label' => 'Create Tickets',
                'description' => 'Can create trouble tickets.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_tickets',
                'group_name' => 'Tickets',
                'label' => 'Read Tickets',
                'description' => 'Can view a Tickets information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_tickets',
                'group_name' => 'Tickets',
                'label' => 'Update Tickets',
                'description' => 'Can update tickets information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_tickets',
                'group_name' => 'Tickets',
                'label' => 'Delete Tickets',
                'description' => 'Can delete tickets.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_groups',
                'group_name' => 'Groups',
                'label' => 'Access groups',
                'description' => 'Can access groups information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_groups',
                'group_name' => 'Groups',
                'label' => 'Create groups',
                'description' => 'Can create trouble groups.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_groups',
                'group_name' => 'Groups',
                'label' => 'Read groups',
                'description' => 'Can view a groups information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_groups',
                'group_name' => 'Groups',
                'label' => 'Update groups',
                'description' => 'Can update groups information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_groups',
                'group_name' => 'Groups',
                'label' => 'Delete groups',
                'description' => 'Can delete groups.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_teams',
                'group_name' => 'Teams',
                'label' => 'Access teams',
                'description' => 'Can access teams information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_teams',
                'group_name' => 'Teams',
                'label' => 'Create teams',
                'description' => 'Can create trouble teams.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_teams',
                'group_name' => 'Teams',
                'label' => 'Read teams',
                'description' => 'Can view a teams information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_teams',
                'group_name' => 'Teams',
                'label' => 'Update teams',
                'description' => 'Can update teams information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_teams',
                'group_name' => 'Teams',
                'label' => 'Delete teams',
                'description' => 'Can delete teams.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_permissions',
                'group_name' => 'Permissions',
                'label' => 'Access permissions',
                'description' => 'Can access permissions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_permissions',
                'group_name' => 'Permissions',
                'label' => 'Create permissions',
                'description' => 'Can create trouble permissions.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_permissions',
                'group_name' => 'Permissions',
                'label' => 'Read permissions',
                'description' => 'Can view a permissions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_permissions',
                'group_name' => 'Permissions',
                'label' => 'Update permissions',
                'description' => 'Can update permissions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_permissions',
                'group_name' => 'Permissions',
                'label' => 'Delete permissions',
                'description' => 'Can delete permissions.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_roles',
                'group_name' => 'Roles',
                'label' => 'Access roles',
                'description' => 'Can access roles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_roles',
                'group_name' => 'Roles',
                'label' => 'Create roles',
                'description' => 'Can create trouble roles.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_roles',
                'group_name' => 'Roles',
                'label' => 'Read roles',
                'description' => 'Can view a roles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_roles',
                'group_name' => 'Roles',
                'label' => 'Update roles',
                'description' => 'Can update roles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_roles',
                'group_name' => 'Roles',
                'label' => 'Delete roles',
                'description' => 'Can delete roles.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Access Position Titles',
                'description' => 'Can access Position Titles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Create Position Titles',
                'description' => 'Can create trouble Position Titles.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Read Position Titles',
                'description' => 'Can view a Position Titles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Update Position Titles',
                'description' => 'Can update Position Titles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Delete Position Titles',
                'description' => 'Can delete Position Titles.',
                'is_system' => false,
                'is_locked' => false,
            ],
        ];

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(
                ['name' => $permission['name']],
                $permission
            );
        }
    }
}