<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            [
                'name' => 'view_owner',
                'group_name' => 'Admin',
                'label' => 'View Owner',
                'description' => 'Can access the owner area.',
                'is_system' => true,
                'is_locked' => true,
            ],
            [
                'name' => 'view_admin',
                'group_name' => 'Admin',
                'label' => 'View Admin',
                'description' => 'Can access the admin area.',
                'is_system' => true,
                'is_locked' => true,
            ],
            [
                'name' => 'create_people',
                'group_name' => 'People',
                'label' => 'Create People',
                'description' => 'Can create people.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_people',
                'group_name' => 'People',
                'label' => 'Access People',
                'description' => 'Can access people information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_people',
                'group_name' => 'People',
                'label' => 'Read People',
                'description' => 'Can View peoples information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_people',
                'group_name' => 'People',
                'label' => 'Update People',
                'description' => 'Can update a persons information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_people',
                'group_name' => 'People',
                'label' => 'Delete People',
                'description' => 'Can delete a person.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_positions',
                'group_name' => 'Positions',
                'label' => 'Access Positions',
                'description' => 'Can access positions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_positions',
                'group_name' => 'Positions',
                'label' => 'Create Positions',
                'description' => 'Can create positions.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_positions',
                'group_name' => 'Positions',
                'label' => 'Read Positions',
                'description' => 'Can view positions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_positions',
                'group_name' => 'Positions',
                'label' => 'Update Positions',
                'description' => 'Can update positions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_positions',
                'group_name' => 'Positions',
                'label' => 'Delete a Position',
                'description' => 'Can delete positions.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_candidates',
                'group_name' => 'Candidates',
                'label' => 'Access Candidates',
                'description' => 'Can access candidates information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_candidates',
                'group_name' => 'Candidates',
                'label' => 'Create Candidates',
                'description' => 'Can create candidates.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_candidates',
                'group_name' => 'Candidates',
                'label' => 'Read Candidates',
                'description' => 'Can view a candidates information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_candidates',
                'group_name' => 'Candidates',
                'label' => 'Update Candidate',
                'description' => 'Can update candidates information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_candidates',
                'group_name' => 'Candidates',
                'label' => 'Delete Candidates',
                'description' => 'Can delete candidates.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_portal',
                'group_name' => 'Portal',
                'label' => 'Access Portal',
                'description' => 'Can enter authenticated Portal areas.',
                'is_system' => true,
                'is_locked' => true,
            ],
            [
                'name' => 'portal_view_dashboard',
                'group_name' => 'Portal',
                'label' => 'View Portal Dashboard',
                'description' => 'Can view the personal Portal dashboard.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_directory',
                'group_name' => 'Portal',
                'label' => 'View Portal Directory',
                'description' => 'Can view Portal people and directory information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_requests',
                'group_name' => 'Portal Requests',
                'label' => 'View Portal Requests',
                'description' => 'Can view requests available through the Portal.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_create_requests',
                'group_name' => 'Portal Requests',
                'label' => 'Create Portal Requests',
                'description' => 'Can submit requests through the Portal.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_resources',
                'group_name' => 'Portal Content',
                'label' => 'View Portal Resources',
                'description' => 'Can view Portal-only resources and documentation.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_program_contacts',
                'group_name' => 'Portal Content',
                'label' => 'View Program Contacts',
                'description' => 'Can view Portal-only program and PMO contacts.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_own_tickets',
                'group_name' => 'Portal Tickets',
                'label' => 'View Own Portal Tickets',
                'description' => 'Can view tickets submitted by the current user in the portal.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_create_tickets',
                'group_name' => 'Portal Tickets',
                'label' => 'Create Portal Tickets',
                'description' => 'Can submit support tickets from the portal.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_positions',
                'group_name' => 'Portal Positions',
                'label' => 'View Portal Positions',
                'description' => 'Can browse portal-safe position information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_tickets',
                'group_name' => 'Tickets',
                'label' => 'Access Tickets',
                'description' => 'Can access tickets information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_tickets',
                'group_name' => 'Tickets',
                'label' => 'Create Tickets',
                'description' => 'Can create trouble tickets.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_tickets',
                'group_name' => 'Tickets',
                'label' => 'Read Tickets',
                'description' => 'Can view a Tickets information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_tickets',
                'group_name' => 'Tickets',
                'label' => 'Update Tickets',
                'description' => 'Can update tickets information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_tickets',
                'group_name' => 'Tickets',
                'label' => 'Delete Tickets',
                'description' => 'Can delete tickets.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_site_settings',
                'group_name' => 'Site Settings',
                'label' => 'Access Site Settings',
                'description' => 'Can view Site Settings in Admin.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_site_settings',
                'group_name' => 'Site Settings',
                'label' => 'Update Site Settings',
                'description' => 'Can update Site Settings in Admin.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_groups',
                'group_name' => 'Groups',
                'label' => 'Access groups',
                'description' => 'Can access groups information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_groups',
                'group_name' => 'Groups',
                'label' => 'Create groups',
                'description' => 'Can create trouble groups.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_groups',
                'group_name' => 'Groups',
                'label' => 'Read groups',
                'description' => 'Can view a groups information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_groups',
                'group_name' => 'Groups',
                'label' => 'Update groups',
                'description' => 'Can update groups information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_groups',
                'group_name' => 'Groups',
                'label' => 'Delete groups',
                'description' => 'Can delete groups.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_teams',
                'group_name' => 'Teams',
                'label' => 'Access teams',
                'description' => 'Can access teams information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_teams',
                'group_name' => 'Teams',
                'label' => 'Create teams',
                'description' => 'Can create trouble teams.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_teams',
                'group_name' => 'Teams',
                'label' => 'Read teams',
                'description' => 'Can view a teams information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_teams',
                'group_name' => 'Teams',
                'label' => 'Update teams',
                'description' => 'Can update teams information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_teams',
                'group_name' => 'Teams',
                'label' => 'Delete teams',
                'description' => 'Can delete teams.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_permissions',
                'group_name' => 'Permissions',
                'label' => 'Access permissions',
                'description' => 'Can access permissions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_permissions',
                'group_name' => 'Permissions',
                'label' => 'Create permissions',
                'description' => 'Can create trouble permissions.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_permissions',
                'group_name' => 'Permissions',
                'label' => 'Read permissions',
                'description' => 'Can view a permissions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_permissions',
                'group_name' => 'Permissions',
                'label' => 'Update permissions',
                'description' => 'Can update permissions information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_permissions',
                'group_name' => 'Permissions',
                'label' => 'Delete permissions',
                'description' => 'Can delete permissions.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_roles',
                'group_name' => 'Roles',
                'label' => 'Access roles',
                'description' => 'Can access roles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_roles',
                'group_name' => 'Roles',
                'label' => 'Create roles',
                'description' => 'Can create trouble roles.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_roles',
                'group_name' => 'Roles',
                'label' => 'Read roles',
                'description' => 'Can view a roles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_roles',
                'group_name' => 'Roles',
                'label' => 'Update roles',
                'description' => 'Can update roles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_roles',
                'group_name' => 'Roles',
                'label' => 'Delete roles',
                'description' => 'Can delete roles.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Access Position Titles',
                'description' => 'Can access Position Titles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'create_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Create Position Titles',
                'description' => 'Can create trouble Position Titles.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'read_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Read Position Titles',
                'description' => 'Can view a Position Titles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'update_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Update Position Titles',
                'description' => 'Can update Position Titles information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'delete_position_titles',
                'group_name' => 'Position Titles',
                'label' => 'Delete Position Titles',
                'description' => 'Can delete Position Titles.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_content_pages',
                'group_name' => 'Content Management',
                'label' => 'Access Content Pages',
                'description' => 'Can view the Content Pages administration area.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'manage_content_pages',
                'group_name' => 'Content Management',
                'label' => 'Manage Content Pages',
                'description' => 'Can create, update, publish, and delete Content Pages.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_page_help',
                'group_name' => 'Application Administration',
                'label' => 'Access Page Help',
                'description' => 'Can view Page Help administration.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'manage_page_help',
                'group_name' => 'Application Administration',
                'label' => 'Manage Page Help',
                'description' => 'Can create, edit, and delete Page Help content.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_organizations',
                'group_name' => 'Organizations',
                'label' => 'Access Organizations',
                'description' => 'Can view organization administration.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'manage_organizations',
                'group_name' => 'Organizations',
                'label' => 'Manage Organizations',
                'description' => 'Can create, update, and delete organizations.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_workflows',
                'group_name' => 'Workflows',
                'label' => 'Access Workflows',
                'description' => 'Can view workflow administration.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'manage_workflows',
                'group_name' => 'Workflows',
                'label' => 'Manage Workflows',
                'description' => 'Can create, update, and delete workflow configuration.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_user_access',
                'group_name' => 'Application Administration',
                'label' => 'Access User Security',
                'description' => 'Can view users, roles, and direct permission assignments.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'manage_user_access',
                'group_name' => 'Application Administration',
                'label' => 'Manage User Security',
                'description' => 'Can change user roles and direct permission assignments.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_component_showcase',
                'group_name' => 'Application Administration',
                'label' => 'Access Component Showcase',
                'description' => 'Can view the internal component and design-system showcase.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'impersonate_users',
                'group_name' => 'Impersonation',
                'label' => 'Impersonate Users',
                'description' => 'Can begin an audited impersonation session.',
                'is_system' => true,
                'is_locked' => true,
            ],
            [
                'name' => 'view_impersonation_log',
                'group_name' => 'Impersonation',
                'label' => 'View Impersonation Log',
                'description' => 'Can review the append-only impersonation audit log.',
                'is_system' => true,
                'is_locked' => true,
            ],
            [
                'name' => 'portal_view_personal_information',
                'group_name' => 'Portal',
                'label' => 'View Personal Information',
                'description' => 'Can view the current user personal profile information.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_all_positions',
                'group_name' => 'Portal Positions',
                'label' => 'View All Portal Positions',
                'description' => 'Can view all positions in the Portal.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_assigned_positions',
                'group_name' => 'Portal Positions',
                'label' => 'View Assigned Portal Positions',
                'description' => 'Can view positions assigned to the current Project Manager.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_candidate_positions',
                'group_name' => 'Portal Candidates',
                'label' => 'View Candidate Positions',
                'description' => 'Can view positions connected to the current candidate.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'portal_view_candidate_progress',
                'group_name' => 'Portal Candidates',
                'label' => 'View Candidate Progress',
                'description' => 'Can view the current candidate workflow progress.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_user_event_log',
                'group_name' => 'User Event Log',
                'label' => 'Access User Event Log',
                'description' => 'Can view user activity and audit events in Admin.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'export_user_event_log',
                'group_name' => 'User Event Log',
                'label' => 'Export User Event Log',
                'description' => 'Can export user activity and audit events.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_data_import',
                'group_name' => 'Data Import',
                'label' => 'Access Data Import',
                'description' => 'Can view Data Import and import history in Admin.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'manage_data_import',
                'group_name' => 'Data Import',
                'label' => 'Manage Data Import',
                'description' => 'Can upload, configure, validate, and execute data imports.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'rollback_data_import',
                'group_name' => 'Data Import',
                'label' => 'Rollback Data Import',
                'description' => 'Can roll back eligible data imports.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'access_custom_fields',
                'group_name' => 'Custom Fields',
                'label' => 'Access Custom Fields',
                'description' => 'Can view custom field configuration in Admin.',
                'is_system' => false,
                'is_locked' => false,
            ],
            [
                'name' => 'manage_custom_fields',
                'group_name' => 'Custom Fields',
                'label' => 'Manage Custom Fields',
                'description' => 'Can create and maintain custom fields for people and positions.',
                'is_system' => false,
                'is_locked' => false,
            ],
        ];

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(
                ['name' => $permission['name']],
                $permission
            );
        }
    }
}