<?php

namespace Database\Seeders;

use App\Models\JobTitle;
use App\Models\Organization;
use App\Models\Position;
use App\Models\PositionActivity;
use App\Models\PositionCustomSkill;
use App\Models\PositionCustomTask;

use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    /**
     * Seed the application's positions table.
     */
    public function run(): void
    {
        /*
        |--------------------------------------------------------------------------
        | Root Organization
        |--------------------------------------------------------------------------
        |
        | Ensure the root organization exists so the seeded position can safely
        | reference the position, sponsoring, and funding organization fields.
        |
        */

        $rootOrganization = Organization::firstOrCreate(
            ['id' => 1],
            [
                'parent_id' => null,
                'name' => 'Org Root',
                'status' => 'active',
                'notes' => 'Default root organization.',
            ]
        );

        // Rebuild hierarchy fields used by the organization dropdown.
        $rootOrganization->rebuildHierarchyFields();

        /*
        |--------------------------------------------------------------------------
        | Job Title Lookup
        |--------------------------------------------------------------------------
        |
        | This assumes JobTitleSeeder has already created the Frontend Developer
        | job title before PositionSeeder runs.
        |
        */

        $frontendDeveloper = JobTitle::where('name', 'Frontend Developer')
            ->firstOrFail();

        /*
        |--------------------------------------------------------------------------
        | Sample Position
        |--------------------------------------------------------------------------
        |
        | Create one fully populated position for testing the Position form,
        | Position details page, inherited skills/tasks, custom skills/tasks,
        | and Position Change History section.
        |
        */

        $position = Position::create([
            'position_code' => 'TEST-001',
            'status' => 'Open',

            // Job title relationship.
            'job_title_id' => $frontendDeveloper->id,

            // Snapshot field. The Position model also keeps this updated.
            'job_title' => $frontendDeveloper->name,

            'experience_level' => 'Experienced',

            // This is also auto-generated by the Position model.
            'labor_category' => 'Frontend Developer - Experienced',

            'certifications_required' => 'Security+ Certification',
            'training_required' => 'Annual Cyber Awareness Training',
            'experience' => '5+ years experience with Vue.js, Laravel, and enterprise application development.',

            'is_essential' => true,
            'travel_required' => false,
            'high_risk_role' => false,

            'location' => 'Washington, DC',
            'building' => 'Building A',

            'mission_description' => 'Supports enterprise modernization initiatives and frontend application development.',
            'component' => 'Technology Services',

            'position_organization_id' => $rootOrganization->id,
            'sponsoring_organization_id' => $rootOrganization->id,
            'funding_organization_id' => $rootOrganization->id,

            'funding_info' => 'FY26 approved funding allocation.',

            'request_to_close' => false,
            'scheduled_to_close' => null,
            'close_date' => null,
            'close_reason' => null,

            'project_team_name' => 'China Team',
            'customer_lead_name' => 'John Smith',
            'customer_created_at' => now()->subDays(30),

            'notes' => 'Seeded testing position for development environment.',
        ]);

        /*
        |--------------------------------------------------------------------------
        | Position-Specific Custom Skills
        |--------------------------------------------------------------------------
        |
        | These supplement the inherited Job Title skills.
        |
        */

        PositionCustomSkill::create([
            'position_id' => $position->id,
            'name' => 'Active Secret Clearance',
            'description' => 'Candidate must be eligible for or already hold an active clearance.',
            'is_active' => true,
            'sort_order' => 1,
        ]);

        PositionCustomSkill::create([
            'position_id' => $position->id,
            'name' => 'GCI Process Familiarity',
            'description' => 'Knowledge of internal GCI workflows and development processes.',
            'is_active' => true,
            'sort_order' => 2,
        ]);

        /*
        |--------------------------------------------------------------------------
        | Position-Specific Custom Tasks
        |--------------------------------------------------------------------------
        |
        | These supplement the inherited Job Title tasks.
        |
        */

        PositionCustomTask::create([
            'position_id' => $position->id,
            'name' => 'Support IRAD modernization work',
            'description' => 'Assist with modernization and refinement of IRAD application modules.',
            'is_active' => true,
            'sort_order' => 1,
        ]);

        PositionCustomTask::create([
            'position_id' => $position->id,
            'name' => 'Prepare customer-facing demos',
            'description' => 'Support demos and walkthroughs for customer stakeholders.',
            'is_active' => true,
            'sort_order' => 2,
        ]);

        /*
        |--------------------------------------------------------------------------
        | Seeded Position Change History
        |--------------------------------------------------------------------------
        |
        | Add realistic fake activity records so the Position Change History
        | table has test data immediately after migrate:fresh --seed.
        |
        | user_id is intentionally null so the seed does not fail if no user
        | exists yet. The UI will display this as "System".
        |
        */

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'status',
            'old_value' => 'Draft',
            'new_value' => 'Open',
            'description' => 'Updated status.',
            'created_at' => now()->subDays(14),
            'updated_at' => now()->subDays(14),
        ]);

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'experience_level',
            'old_value' => 'Novice',
            'new_value' => 'Experienced',
            'description' => 'Updated experience level.',
            'created_at' => now()->subDays(12),
            'updated_at' => now()->subDays(12),
        ]);

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'high_risk_role',
            'old_value' => 'No',
            'new_value' => 'Yes',
            'description' => 'Updated high risk role.',
            'created_at' => now()->subDays(10),
            'updated_at' => now()->subDays(10),
        ]);

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'location',
            'old_value' => 'Washington, DC',
            'new_value' => 'Arlington, VA',
            'description' => 'Updated location.',
            'created_at' => now()->subDays(7),
            'updated_at' => now()->subDays(7),
        ]);

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'funding_info',
            'old_value' => 'FY25 approved funding allocation.',
            'new_value' => 'FY26 approved funding allocation.',
            'description' => 'Updated funding information.',
            'created_at' => now()->subDays(3),
            'updated_at' => now()->subDays(3),
        ]);
    }
}