<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\Position;
use App\Models\PositionActivity;

use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    /**
     * Seed the application's positions table.
     */
    public function run(): void
    {
        /*
        |--------------------------------------------------------------------------
        | Root Organization
        |--------------------------------------------------------------------------
        |
        | Ensure the root organization exists so the seeded position can safely
        | reference the position, sponsoring, and funding organization fields.
        |
        */

        $rootOrganization = Organization::firstOrCreate(
            ['id' => 1],
            [
                'parent_id' => null,
                'name' => 'Org Root',
                'status' => 'active',
                'notes' => 'Default root organization.',
            ]
        );

        // Rebuild hierarchy fields used by the organization dropdown.
        $rootOrganization->rebuildHierarchyFields();

        /*
        |--------------------------------------------------------------------------
        | Sample Position
        |--------------------------------------------------------------------------
        |
        | Create one fully populated position for testing the Position form,
        | Position details page, and Position Change History section.
        |
        */

        $position = Position::create([
            'position_code' => 'TEST-001',
            'status' => 'Open',

            'job_title' => 'Frontend Developer',
            'experience_level' => 'Experienced',

            // This is also auto-generated by the Position model.
            'labor_category' => 'Frontend Developer - Experienced',

            'certifications_required' => 'Security+ Certification',
            'training_required' => 'Annual Cyber Awareness Training',
            'experience' => '5+ years experience with Vue.js, Laravel, and enterprise application development.',

            'is_essential' => true,
            'travel_required' => false,
            'high_risk_role' => false,

            'location' => 'Washington, DC',
            'building' => 'Building A',

            'mission_description' => 'Supports enterprise modernization initiatives and frontend application development.',
            'component' => 'Technology Services',

            'position_organization_id' => $rootOrganization->id,
            'sponsoring_organization_id' => $rootOrganization->id,
            'funding_organization_id' => $rootOrganization->id,

            'funding_info' => 'FY26 approved funding allocation.',

            'request_to_close' => false,
            'scheduled_to_close' => null,
            'close_date' => null,
            'close_reason' => null,

            'project_team_name' => 'China Team',
            'customer_lead_name' => 'John Smith',
            'customer_created_at' => now()->subDays(30),

            'notes' => 'Seeded testing position for development environment.',
        ]);

        /*
        |--------------------------------------------------------------------------
        | Seeded Position Change History
        |--------------------------------------------------------------------------
        |
        | Add realistic fake activity records so the Position Change History
        | table has test data immediately after migrate:fresh --seed.
        |
        | user_id is set to 1, assuming your Owner/Admin user is seeded first.
        |
        */

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'status',
            'old_value' => 'Draft',
            'new_value' => 'Open',
            'description' => 'Updated status.',
            'created_at' => now()->subDays(14),
            'updated_at' => now()->subDays(14),
        ]);

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'experience_level',
            'old_value' => 'Novice',
            'new_value' => 'Experienced',
            'description' => 'Updated experience level.',
            'created_at' => now()->subDays(12),
            'updated_at' => now()->subDays(12),
        ]);

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'high_risk_role',
            'old_value' => 'No',
            'new_value' => 'Yes',
            'description' => 'Updated high risk role.',
            'created_at' => now()->subDays(10),
            'updated_at' => now()->subDays(10),
        ]);

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'location',
            'old_value' => 'Washington, DC',
            'new_value' => 'Arlington, VA',
            'description' => 'Updated location.',
            'created_at' => now()->subDays(7),
            'updated_at' => now()->subDays(7),
        ]);

        PositionActivity::create([
            'position_id' => $position->id,
            'user_id' => null,
            'action' => 'updated',
            'field_name' => 'funding_info',
            'old_value' => 'FY25 approved funding allocation.',
            'new_value' => 'FY26 approved funding allocation.',
            'description' => 'Updated funding information.',
            'created_at' => now()->subDays(3),
            'updated_at' => now()->subDays(3),
        ]);
    }
}