<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\Position;

use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    /**
     * Seed the application's positions table.
     */
    public function run(): void
    {
        /*
        |--------------------------------------------------------------------------
        | Root Organization
        |--------------------------------------------------------------------------
        |
        | Ensure the root organization exists so the seeded position can
        | safely reference organization relationships.
        |
        */

        $rootOrganization = Organization::firstOrCreate(
            ['id' => 1],
            [
                'parent_id' => null,
                'name' => 'Org Root',
                'status' => 'active',
                'notes' => 'Default root organization.',
            ]
        );

        // Rebuild hierarchy/path fields used by organization dropdowns.
        $rootOrganization->rebuildHierarchyFields();

        /*
        |--------------------------------------------------------------------------
        | Sample Position
        |--------------------------------------------------------------------------
        |
        | Creates one fully populated position record for development/testing.
        |
        */

        Position::create([

            /*
            |--------------------------------------------------------------------------
            | Core Information
            |--------------------------------------------------------------------------
            */

            'position_code' => 'TEST-001',

            'status' => 'Open',

            'job_title' => 'Frontend Developer',

            'experience_level' => 'Experienced',

            // Auto-generated by Position model boot() logic.
            'labor_category' => 'Frontend Developer - Experienced',

            /*
            |--------------------------------------------------------------------------
            | Requirements
            |--------------------------------------------------------------------------
            */

            'certifications_required' =>
                'Security+ Certification',

            'training_required' =>
                'Annual Cyber Awareness Training',

            'experience' =>
                '5+ years experience with Vue.js, Laravel, and enterprise application development.',

            /*
            |--------------------------------------------------------------------------
            | Flags
            |--------------------------------------------------------------------------
            */

            'is_essential' => true,

            'travel_required' => false,

            'high_risk_role' => false,

            /*
            |--------------------------------------------------------------------------
            | Location
            |--------------------------------------------------------------------------
            */

            'location' => 'Washington, DC',

            'building' => 'Building A',

            /*
            |--------------------------------------------------------------------------
            | Mission / Component
            |--------------------------------------------------------------------------
            */

            'mission_description' =>
                'Supports enterprise modernization initiatives and frontend application development.',

            'component' => 'Technology Services',

            /*
            |--------------------------------------------------------------------------
            | Organizations
            |--------------------------------------------------------------------------
            */

            'position_organization_id' =>
                $rootOrganization->id,

            'sponsoring_organization_id' =>
                $rootOrganization->id,

            'funding_organization_id' =>
                $rootOrganization->id,

            /*
            |--------------------------------------------------------------------------
            | Funding
            |--------------------------------------------------------------------------
            */

            'funding_info' =>
                'FY26 approved funding allocation.',

            /*
            |--------------------------------------------------------------------------
            | Closure Workflow
            |--------------------------------------------------------------------------
            */

            'request_to_close' => false,

            'scheduled_to_close' => null,

            'close_date' => null,

            'close_reason' => null,

            /*
            |--------------------------------------------------------------------------
            | Existing / Legacy Fields
            |--------------------------------------------------------------------------
            */

            'project_team_name' => 'China Team',

            'customer_lead_name' => 'John Smith',

            'customer_created_at' =>
                now()->subDays(30),

            'notes' =>
                'Seeded testing position for development environment.',
        ]);
    }
}