<script setup lang="ts">
import { useForm } from '@inertiajs/vue3';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Textarea } from '@/components/ui/textarea';
const props=defineProps<{messageBox?:any;roles:{name:string;label:string}[];permissions:{name:string;label:string;group_name:string}[]}>();
const b=props.messageBox;
const form=useForm({name:b?.name??'',title:b?.title??'',content_html:b?.content_html??'',display_type:b?.display_type??'modal',audience:b?.audience??'everyone',audience_values:b?.audience_values??[],page_patterns:(b?.page_patterns??['*']).join('\n'),trigger_type:b?.trigger_type??'automatic',trigger_key:b?.trigger_key??'',show_once:b?.show_once??false,dismissible:b?.dismissible??true,priority:b?.priority??100,actions:b?.actions??[],form_fields:b?.form_fields??[],is_active:b?.is_active??true,starts_at:b?.starts_at?.slice(0,16)??'',ends_at:b?.ends_at?.slice(0,16)??''});
function addAction(){if(form.actions.length<3)form.actions.push({label:'',url:''});} function addField(){form.form_fields.push({name:'',label:'',type:'text',required:false});}
function submit(){form.transform(d=>({...d,page_patterns:d.page_patterns.split('\n').map((x:string)=>x.trim()).filter(Boolean),starts_at:d.starts_at||null,ends_at:d.ends_at||null})); b?form.put(`/admin/message-boxes/${b.id}`):form.post('/admin/message-boxes');}
</script>
<template><form class="space-y-6" @submit.prevent="submit">
<div class="grid gap-4 md:grid-cols-2"><label class="text-sm font-medium">Internal name<Input v-model="form.name" class="mt-1"/></label><label class="text-sm font-medium">Display title<Input v-model="form.title" class="mt-1"/></label></div>
<label class="block text-sm font-medium">Message HTML<Textarea v-model="form.content_html" rows="8" class="mt-1 font-mono"/></label>
<div class="grid gap-4 md:grid-cols-3"><label class="text-sm font-medium">Display type<select v-model="form.display_type" class="mt-1 h-10 w-full rounded-md border bg-background px-3"><option value="modal">Modal popup</option><option value="top_banner">Top banner</option><option value="bottom_banner">Bottom banner</option></select></label><label class="text-sm font-medium">Priority<Input v-model.number="form.priority" type="number" class="mt-1"/></label><label class="text-sm font-medium">Audience<select v-model="form.audience" class="mt-1 h-10 w-full rounded-md border bg-background px-3"><option value="everyone">Everyone</option><option value="roles">Specific roles</option><option value="permissions">Specific permissions</option></select></label></div>
<div v-if="form.audience==='roles'" class="rounded-md border p-4"><div class="mb-2 font-medium">Roles</div><label v-for="r in roles" :key="r.name" class="mr-5 inline-flex gap-2"><input v-model="form.audience_values" type="checkbox" :value="r.name"/>{{r.label}}</label></div>
<div v-if="form.audience==='permissions'" class="max-h-64 overflow-auto rounded-md border p-4"><div class="mb-2 font-medium">Permissions</div><label v-for="p in permissions" :key="p.name" class="mr-5 inline-flex gap-2"><input v-model="form.audience_values" type="checkbox" :value="p.name"/>{{p.label}}</label></div>
<label class="block text-sm font-medium">Page patterns <span class="font-normal text-muted-foreground">(one per line; * = everywhere, /portal/* = Portal)</span><Textarea v-model="form.page_patterns" rows="4" class="mt-1 font-mono"/></label>
<div class="grid gap-4 md:grid-cols-3"><label class="text-sm font-medium">Trigger<select v-model="form.trigger_type" class="mt-1 h-10 w-full rounded-md border bg-background px-3"><option value="automatic">Automatic</option><option value="manual">Manual / programmatic</option></select></label><label v-if="form.trigger_type==='manual'" class="text-sm font-medium">Trigger key<Input v-model="form.trigger_key" class="mt-1" placeholder="candidate-help"/></label><label class="text-sm font-medium">Starts at<Input v-model="form.starts_at" type="datetime-local" class="mt-1"/></label><label class="text-sm font-medium">Ends at<Input v-model="form.ends_at" type="datetime-local" class="mt-1"/></label></div>
<div class="flex flex-wrap gap-6"><label><input v-model="form.is_active" type="checkbox" class="mr-2"/>Active</label><label><input v-model="form.dismissible" type="checkbox" class="mr-2"/>Dismissible</label><label><input v-model="form.show_once" type="checkbox" class="mr-2"/>Show once per user</label></div>
<section class="rounded-md border p-4"><div class="flex items-center justify-between"><h3 class="font-semibold">Action buttons (up to 3)</h3><Button type="button" variant="outline" @click="addAction">Add button</Button></div><div v-for="(a,i) in form.actions" :key="i" class="mt-3 grid gap-2 md:grid-cols-[1fr_2fr_auto]"><Input v-model="a.label" placeholder="Button label"/><Input v-model="a.url" placeholder="/portal/... or https://..."/><Button type="button" variant="ghost" @click="form.actions.splice(i,1)">Remove</Button></div></section>
<section class="rounded-md border p-4"><div class="flex items-center justify-between"><h3 class="font-semibold">Optional form fields</h3><Button type="button" variant="outline" @click="addField">Add field</Button></div><div v-for="(f,i) in form.form_fields" :key="i" class="mt-3 grid gap-2 md:grid-cols-[1fr_1fr_1fr_auto_auto]"><Input v-model="f.name" placeholder="field_name"/><Input v-model="f.label" placeholder="Label"/><select v-model="f.type" class="h-10 rounded-md border bg-background px-3"><option>text</option><option>email</option><option>textarea</option><option>checkbox</option></select><label class="self-center"><input v-model="f.required" type="checkbox"/> Required</label><Button type="button" variant="ghost" @click="form.form_fields.splice(i,1)">Remove</Button></div></section>
<div v-if="Object.keys(form.errors).length" class="rounded-md border border-destructive p-3 text-sm text-destructive"><div v-for="(e,k) in form.errors" :key="k">{{e}}</div></div>
<Button type="submit" :disabled="form.processing">{{b?'Save Message Box':'Create Message Box'}}</Button>
</form></template>
