<?php

namespace App\Support\ListDefinitions;

class CandidateDefinition
{
    public static function get()
    {
        return [
            'list_key' => 'candidates',
            'default_sort' => 'candidates.created_at',
            'default_direction' => 'desc',

            'columns' => [
                [
                    'key' => 'id',
                    'label' => 'ID',
                    'db_field' => 'candidates.id',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 1,
                ],
                [
                    'key' => 'candidate_code',
                    'label' => 'Candidate Code',
                    'db_field' => 'candidates.candidate_code',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 2,
                ],
                [
                    'key' => 'status',
                    'label' => 'Status',
                    'db_field' => 'candidates.status',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 3,
                ],
                [
                    'key' => 'person_name',
                    'label' => 'Person',
                    'db_field' => 'people.last_name',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 4,
                ],
                [
                    'key' => 'person_code',
                    'label' => 'Person Code',
                    'db_field' => 'people.person_code',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 5,
                ],
                [
                    'key' => 'position_title',
                    'label' => 'Position',
                    'db_field' => 'positions.job_title',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 6,
                ],
                [
                    'key' => 'position_code',
                    'label' => 'Position Code',
                    'db_field' => 'positions.position_code',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 7,
                ],
                [
                    'key' => 'candidate_fbr',
                    'label' => 'FBR',
                    'db_field' => 'candidates.candidate_fbr',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 8,
                ],
                [
                    'key' => 'submitted_at',
                    'label' => 'Submitted At',
                    'db_field' => 'candidates.submitted_at',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 9,
                ],
                [
                    'key' => 'submitted_by',
                    'label' => 'Submitted By',
                    'db_field' => 'submitted_by_people.last_name',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 10,
                ],
                [
                    'key' => 'scheduled_start_date',
                    'label' => 'Scheduled Start',
                    'db_field' => 'candidates.scheduled_start_date',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 11,
                ],
                [
                    'key' => 'created_at',
                    'label' => 'Created',
                    'db_field' => 'candidates.created_at',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 12,
                ],
            ],
        ];
    }
}