<?php

namespace App\Support\ListDefinitions;

class PositionsDefinition
{
    public static function get()
    {
        return [
            'list_key' => 'positions',
            'default_sort' => 'created_at',
            'default_direction' => 'desc',

            'columns' => [
                [
                    'key' => 'position_code',
                    'label' => 'Code',
                    'db_field' => 'positions.position_code',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 1,
                ],
                [
                    'key' => 'job_title',
                    'label' => 'Job Title',
                    'db_field' => 'positions.job_title',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 2,
                ],
                [
                    'key' => 'experience_level',
                    'label' => 'Experience Level',
                    'db_field' => 'positions.experience_level',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 3,
                ],
                [
                    'key' => 'labor_category',
                    'label' => 'Labor Category',
                    'db_field' => 'positions.labor_category',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 4,
                ],
                [
                    'key' => 'status',
                    'label' => 'Status',
                    'db_field' => 'positions.status',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 5,
                ],
                [
                    'key' => 'location',
                    'label' => 'Location',
                    'db_field' => 'positions.location',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 6,
                ],
                [
                    'key' => 'building',
                    'label' => 'Building',
                    'db_field' => 'positions.building',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 7,
                ],
                [
                    'key' => 'component',
                    'label' => 'Component',
                    'db_field' => 'positions.component',
                    'sortable' => true,
                    'searchable' => true,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => true,
                    'default_order' => 8,
                ],
                [
                    'key' => 'is_essential',
                    'label' => 'Essential',
                    'db_field' => 'positions.is_essential',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 9,
                ],
                [
                    'key' => 'travel_required',
                    'label' => 'Travel Required',
                    'db_field' => 'positions.travel_required',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 10,
                ],
                [
                    'key' => 'high_risk_role',
                    'label' => 'High Risk Role',
                    'db_field' => 'positions.high_risk_role',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 11,
                ],
                [
                    'key' => 'scheduled_to_close',
                    'label' => 'Scheduled To Close',
                    'db_field' => 'positions.scheduled_to_close',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 12,
                ],
                [
                    'key' => 'close_date',
                    'label' => 'Close Date',
                    'db_field' => 'positions.close_date',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 13,
                ],
                [
                    'key' => 'created_at',
                    'label' => 'Created',
                    'db_field' => 'positions.created_at',
                    'sortable' => true,
                    'searchable' => false,
                    'hideable' => true,
                    'exportable' => true,
                    'default_visible' => false,
                    'default_order' => 99,
                ],
            ],
        ];
    }
}