import type { Component } from 'vue';
import {
    BadgeCheck,
    BarChart3,
    BookOpenCheck,
    Boxes,
    BriefcaseBusiness,
    Building2,
    CircleUserRound,
    ClipboardList,
    FileBarChart,
    FileText,
    Group,
    HelpCircle,
    KeyRound,
    LayoutDashboard,
    LifeBuoy,
    ListChecks,
    ListPlus,
    ListTodo,
    Palette,
    Plus,
    Settings,
    ShieldCheck,
    Tags,
    UserCog,
    UserSearch,
    Users,
    Workflow,
} from 'lucide-vue-next';

export type AdminPortalGroup =
    | 'People and Workforce'
    | 'Positions and Assignments'
    | 'Requests and Workflows'
    | 'Support'
    | 'Organizations and Structure'
    | 'Content and Help'
    | 'Security and Access'
    | 'Configuration'
    | 'Reporting'
    | 'Site Settings';

export type AdminPortalItem = {
    id: string;
    title: string;
    description: string;
    href?: string;
    group: AdminPortalGroup;
    icon: Component;
    permission?: string;
    permissionsAny?: string[];
    keywords: string[];
    action?: string;
    quick?: boolean;
    comingSoon?: boolean;
};

export const adminPortalGroupOrder: AdminPortalGroup[] = [
    'People and Workforce',
    'Positions and Assignments',
    'Requests and Workflows',
    'Support',
    'Organizations and Structure',
    'Content and Help',
    'Security and Access',
    'Configuration',
    'Reporting',
    'Site Settings',
];

export const adminPortalItems: AdminPortalItem[] = [
    {
        id: 'people',
        title: 'People',
        description: 'Manage personnel records, contact information, organizational assignments, access, and files.',
        href: '/portal/people',
        group: 'People and Workforce',
        icon: CircleUserRound,
        permission: 'access_people',
        keywords: ['people', 'person', 'employee', 'staff', 'workforce', 'directory', 'member'],
        action: 'Manage',
    },
    {
        id: 'create-person',
        title: 'Create Person',
        description: 'Add a new person and configure their organization, contact information, roles, and attachments.',
        href: '/portal/people/create',
        group: 'People and Workforce',
        icon: Plus,
        permission: 'create_people',
        keywords: ['create person', 'add person', 'new employee', 'new staff', 'onboard person'],
        action: 'Create',
        quick: true,
    },
    {
        id: 'candidates',
        title: 'Candidates',
        description: 'Manage candidates, linked positions, statuses, and workflow progress.',
        href: '/portal/candidates',
        group: 'People and Workforce',
        icon: UserSearch,
        permission: 'access_candidates',
        keywords: ['candidate', 'applicant', 'recruiting', 'hiring', 'pipeline'],
        action: 'Manage',
    },
    {
        id: 'create-candidate',
        title: 'Create Candidate',
        description: 'Connect an eligible person to a position and begin a candidate workflow.',
        href: '/portal/candidates/create',
        group: 'People and Workforce',
        icon: Plus,
        permission: 'create_candidates',
        keywords: ['create candidate', 'add candidate', 'new applicant', 'start candidate'],
        action: 'Create',
        quick: true,
    },
    {
        id: 'job-titles',
        title: 'Job Titles',
        description: 'Manage job titles and their default skills and task requirements.',
        href: '/portal/job-titles',
        group: 'People and Workforce',
        icon: BadgeCheck,
        permission: 'access_positions',
        keywords: ['job title', 'titles', 'occupation', 'role title', 'skills', 'tasks'],
        action: 'Manage',
    },
    {
        id: 'job-title-requirements',
        title: 'Job Title Requirements',
        description: 'Review required skills, desired skills, and tasks across job titles.',
        href: '/portal/job-title-requirements',
        group: 'People and Workforce',
        icon: ListChecks,
        permission: 'access_positions',
        keywords: ['requirements', 'job title skills', 'job title tasks', 'required skills', 'desired skills'],
        action: 'Review',
    },
    {
        id: 'positions',
        title: 'Positions',
        description: 'Manage staffing requirements, position details, assignments, candidates, and mission needs.',
        href: '/portal/positions',
        group: 'Positions and Assignments',
        icon: BriefcaseBusiness,
        permission: 'access_positions',
        keywords: ['position', 'positions', 'requisition', 'staffing', 'vacancy', 'opening'],
        action: 'Manage',
    },
    {
        id: 'create-position',
        title: 'Create Position',
        description: 'Add a staffing position and define its requirements, organizations, and operational details.',
        href: '/portal/positions/create',
        group: 'Positions and Assignments',
        icon: Plus,
        permission: 'create_positions',
        keywords: ['create position', 'add position', 'new requisition', 'new opening'],
        action: 'Create',
        quick: true,
    },
    {
        id: 'position-assignments',
        title: 'Position Assignments',
        description: 'Create and maintain person-to-position assignments.',
        href: '/portal/positions',
        group: 'Positions and Assignments',
        icon: ClipboardList,
        permissionsAny: ['access_positions', 'update_positions'],
        keywords: ['assignment', 'assign person', 'position assignment', 'staff position'],
        action: 'Create',
    },
    {
        id: 'workflows',
        title: 'Candidate Workflows',
        description: 'Configure workflow definitions, steps, sequence, and statuses used by candidates.',
        href: '/workflows',
        group: 'Requests and Workflows',
        icon: Workflow,
        permission: 'view_admin',
        keywords: ['workflow', 'workflows', 'workflow steps', 'workflow statuses', 'candidate stages', 'process'],
        action: 'Configure',
    },
    {
        id: 'create-workflow',
        title: 'Create Workflow',
        description: 'Create a workflow and define the steps used to advance candidates.',
        href: '/workflows/create',
        group: 'Requests and Workflows',
        icon: Plus,
        permission: 'view_admin',
        keywords: ['create workflow', 'add workflow', 'new process', 'workflow status'],
        action: 'Create',
    },
    {
        id: 'requests',
        title: 'Requests',
        description: 'Manage operational requests and approvals when the dedicated Requests module is introduced.',
        group: 'Requests and Workflows',
        icon: ClipboardList,
        permission: 'view_admin',
        keywords: ['request', 'requests', 'approval', 'operational request'],
        comingSoon: true,
    },
    {
        id: 'tickets',
        title: 'Support Tickets',
        description: 'Review, assign, update, watch, and resolve support tickets.',
        href: '/admin/tickets',
        group: 'Support',
        icon: LifeBuoy,
        permission: 'access_tickets',
        keywords: ['ticket', 'tickets', 'support', 'help desk', 'issue', 'trouble ticket'],
        action: 'Review',
        quick: true,
    },
    {
        id: 'ticket-categories',
        title: 'Ticket Categories',
        description: 'Ticket categorization is currently managed through the existing support workflow.',
        href: '/admin/tickets',
        group: 'Support',
        icon: Tags,
        permission: 'access_tickets',
        keywords: ['ticket category', 'categories', 'support category', 'request type'],
        action: 'Review',
    },
    {
        id: 'organizations',
        title: 'Organizations',
        description: 'Manage the organizational structure used throughout IRAD.',
        href: '/admin/organizations',
        group: 'Organizations and Structure',
        icon: Building2,
        permission: 'access_organizations',
        keywords: ['organization', 'organizations', 'org', 'company', 'structure'],
        action: 'Manage',
    },
    {
        id: 'groups',
        title: 'Groups',
        description: 'Manage organizational and access-related groups.',
        href: '/admin/groups',
        group: 'Organizations and Structure',
        icon: Group,
        permission: 'view_admin',
        keywords: ['group', 'groups', 'organizational group', 'membership'],
        action: 'Manage',
    },
    {
        id: 'teams',
        title: 'Teams',
        description: 'Manage teams used for program and workforce organization.',
        href: '/admin/teams',
        group: 'Organizations and Structure',
        icon: Boxes,
        permission: 'view_admin',
        keywords: ['team', 'teams', 'project team', 'work team'],
        action: 'Manage',
    },

    {
        id: 'custom-fields',
        title: 'Custom Fields',
        description: 'Configure installation-specific fields for Person and Position records.',
        href: '/admin/custom-fields',
        group: 'Configuration',
        icon: ListPlus,
        permission: 'access_custom_fields',
        keywords: ['custom fields', 'other information', 'person fields', 'position fields', 'configuration'],
        action: 'Configure',
        quick: true,
    },
    {
        id: 'content-pages',
        title: 'Content Pages',
        description: 'Manage program information, contacts, resources, FAQs, policies, documentation, announcements, and help links.',
        href: '/admin/content-pages',
        group: 'Content and Help',
        icon: FileText,
        permission: 'access_content_pages',
        keywords: ['content pages', 'tiny cms', 'cms', 'program overview', 'program details', 'contacts', 'resources', 'faqs', 'policies', 'documentation', 'announcements', 'help links'],
        action: 'Manage',
        quick: true,
    },
    {
        id: 'create-content-page',
        title: 'Create Content Page',
        description: 'Create a Public, Portal, or shared informational page.',
        href: '/admin/content-pages/create',
        group: 'Content and Help',
        icon: Plus,
        permission: 'manage_content_pages',
        keywords: ['create page', 'add page', 'new content', 'new faq', 'new policy', 'new resource'],
        action: 'Create',
    },
    {
        id: 'page-help',
        title: 'Page Help',
        description: 'Manage contextual Help content displayed throughout Public, Portal, and Admin pages.',
        href: '/admin/page-help',
        group: 'Content and Help',
        icon: BookOpenCheck,
        permission: 'access_page_help',
        keywords: ['page help', 'help', 'instructions', 'documentation', 'contextual help', 'question mark'],
        action: 'Manage',
        quick: true,
    },
    {
        id: 'create-page-help',
        title: 'Create Help Page',
        description: 'Add contextual instructions for a page or workflow.',
        href: '/admin/page-help/create',
        group: 'Content and Help',
        icon: Plus,
        permission: 'manage_page_help',
        keywords: ['create help', 'add help page', 'new instructions', 'page documentation'],
        action: 'Create',
    },
    {
        id: 'users-access',
        title: 'Users and Access',
        description: 'Review users and manage their assigned roles and direct permissions.',
        href: '/admin/users',
        group: 'Security and Access',
        icon: Users,
        permission: 'access_user_access',
        keywords: ['user', 'users', 'user permissions', 'access', 'account', 'security'],
        action: 'Manage',
    },
    {
        id: 'roles',
        title: 'Roles',
        description: 'Create roles and maintain their permission sets.',
        href: '/admin/roles',
        group: 'Security and Access',
        icon: ShieldCheck,
        permission: 'access_roles',
        keywords: ['role', 'roles', 'owner', 'admin', 'pmo', 'candidate', 'project manager'],
        action: 'Manage',
        quick: true,
    },
    {
        id: 'permissions',
        title: 'Permissions',
        description: 'Review and maintain the application permission catalog.',
        href: '/admin/permissions',
        group: 'Security and Access',
        icon: KeyRound,
        permission: 'access_permissions',
        keywords: ['permission', 'permissions', 'authorization', 'access control', 'security'],
        action: 'Manage',
    },
    {
        id: 'impersonation',
        title: 'Impersonate User',
        description: 'Begin an audited support or troubleshooting session as another user.',
        href: '/admin/impersonation',
        group: 'Security and Access',
        icon: UserCog,
        permission: 'impersonate_users',
        keywords: ['impersonate', 'impersonation', 'switch user', 'support session', 'audit log'],
        action: 'Open',
    },
    {
        id: 'component-showcase',
        title: 'Component Showcase',
        description: 'Review reusable interface patterns and design standards.',
        href: '/admin/component-showcase',
        group: 'Configuration',
        icon: Palette,
        permission: 'access_component_showcase',
        keywords: ['component', 'showcase', 'design system', 'ui', 'patterns'],
        action: 'Review',
    },
    {
        id: 'application-configuration',
        title: 'Application Configuration',
        description: 'Use organizations, teams, groups, roles, workflows, and Help to configure IRAD.',
        href: '/admin',
        group: 'Configuration',
        icon: Settings,
        permission: 'view_admin',
        keywords: ['configuration', 'config', 'settings', 'system lists', 'reference data'],
        action: 'Review',
    },
    {
        id: 'people-reporting',
        title: 'People Reporting',
        description: 'Open the People list to filter visible data and export CSV reports.',
        href: '/portal/people',
        group: 'Reporting',
        icon: FileBarChart,
    FileText,
        permission: 'access_people',
        keywords: ['people report', 'people export', 'employee report', 'csv'],
        action: 'Open',
    },
    {
        id: 'position-reporting',
        title: 'Position Reporting',
        description: 'Open Positions to filter staffing data and export CSV reports.',
        href: '/portal/positions',
        group: 'Reporting',
        icon: BarChart3,
        permission: 'access_positions',
        keywords: ['position report', 'staffing report', 'position export', 'csv'],
        action: 'Open',
    },
    {
        id: 'ticket-reporting',
        title: 'Ticket Reporting',
        description: 'Open Support Tickets to filter operational issues and export CSV reports.',
        href: '/admin/tickets',
        group: 'Reporting',
        icon: FileBarChart,
    FileText,
        permission: 'access_tickets',
        keywords: ['ticket report', 'support report', 'ticket export', 'csv'],
        action: 'Open',
    },
    {
        id: 'site-settings',
        title: 'Site Settings',
        description: 'Manage portal names, colors, program details, homepage content, and footer text.',
        href: '/admin/site-settings',
        group: 'Site Settings',
        icon: Settings,
        permission: 'access_site_settings',
        keywords: ['site settings', 'branding', 'logo', 'logos', 'colors', 'text', 'program information', 'homepage', 'footer'],
        action: 'Configure',
        quick: true,
    },
];

export function normalizeAdminPortalSearch(value: string): string {
    return value
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

export function adminPortalSearchText(item: AdminPortalItem): string {
    return normalizeAdminPortalSearch([
        item.title,
        item.description,
        item.group,
        item.action ?? '',
        ...item.keywords,
    ].join(' '));
}
