<h2>{{ $alert->title }}</h2>

@if ($alert->message)
    <p>{{ $alert->message }}</p>
@endif

@if ($alert->action_url)
    <p>
        <a href="{{ url($alert->action_url) }}">
            View Item
        </a>
    </p>
@endif

<p style="font-size: 12px; color: #666;">
    This message was generated by the alert system.
</p>